# numpy

In [16]:
# import numpy
a=numpy.array(1)#creating a ndarray using the numpy.array() method or function
print(type(a))
#b=numpy.array(1,2) #shows error u need to use any array type object inside the array method to pass more than one value
c=numpy.array([1,2,3])
#or
d=numpy.array((0,9,8))
print(c)
print(d)
print(a)
#accessing particular elements of ndarray
print(c[0])#using [] bcz we know syntax is using [] in python to access list



<class 'numpy.ndarray'>
[1 2 3]
[0 9 8]
1
1


# dimension in arrays

In [36]:
import numpy as np
a=np.array(23)
b=np.array([1,2,3])#1 square brac
#c=np.array([1,2,3],[4,5,6]) will show error bcz see here we are giving two different lists in the array function directly with using any kind of array onj like list,tuple e.t.c
d=np.array([[1,2,3],[4,5,6]])#2sq
e=np.array([[[1,2,3],[4,5,6]]])#3sq
print(a.ndim)
print(b.ndim)
print(d.ndim)
print(e.ndim)
'''note
1)if 0 square bracket 0 dimensio
1 square bractet 1 dimension
2 square bractet 2 dimension
3 square bractet 3 dimension(note that after 2 square brac u can give some no of array type objects) if not see below
'''
k=np.array([[[1,2,3]],[1,2,3]])
print(k.ndim)#it prints one bcz after one square brackets i.e, in the first list itself we gave 2 lists eventhough in them the first one is of two dimensional but overall as in first phase brackets itself we are giving values so the ndarray is of 1 dimension


0
1
2
3
1


/var/folders/j2/7vzyj65535sdpxn_vd38sncm0000gn/T/ipykernel_5673/818877459.py:17: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  k=np.array([[[1,2,3]],[1,2,3]])




# higher dimension

In [40]:
import numpy as kk
a=kk.array([1,2,3,4],ndmin=5)#NOTE: ndmin HERE NOT ndim
print(a)
"""In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array."""

[[[[[1 2 3 4]]]]]


'In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.'